# -*- coding: utf-8 -*-
"""Landmark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6zpxT5Vsj3HQNwhuKCMMXk38jvP2kFg
"""


def detect_landmarks(path):
    """Detects landmarks in the file."""
    import os 
    os.environ['GOOGLE_APPLICATION_CREDENTIALS']="C:/Users/Alex/Downloads/qwiklabs-gcp-04-4c39ff72a2f8-11f562a2fc07.json"
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient()

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.Image(content=content)

    response = client.landmark_detection(image=image)
    landmarks = response.landmark_annotations
    print('Landmarks:')
    places=[]
    for landmark in landmarks:
        x=''
        x=x+(landmark.description)
        for location in landmark.locations:
            lat_lng = location.lat_lng
            x=x+('\s Latitude {}'.format(lat_lng.latitude))
            x=x+('\s Longitude {}'.format(lat_lng.longitude))
        places.append(x)

    if response.error.message:
        raise Exception('{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(response.error.message))
    return places
    

    
